aws_region = "eu-west-1"
region = "eu-west-1"
aws_access_key = "replace me"
aws_secret_key = "replace me"
environment = "staging"
ecr_api_url = "<aws_account>.dkr.ecr.eu-west-1.amazonaws.com/<ecr_repo>"