version: 2.1

orbs:
  python: circleci/python@1.2


jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: make build
      - run: make test
      - run: bash ./scripts/push.sh
  deploy:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: make deploy
# Invoke jobs via workflows
workflows:
  main:
    jobs:
      - build-and-test:
          name: build-and-test
          branches:
            only:
              - main
      - deploy:
          name: deploy
          requires:
            - build-and-test
          branches:
          only:
            - main